/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_simplesim_controller */

#ifndef _Included_com_example_simplesim_controller
#define _Included_com_example_simplesim_controller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_simplesim_controller
 * Method:    gearUp
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_simplesim_controller_gearUp
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_simplesim_controller
 * Method:    gearDown
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_simplesim_controller_gearDown
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
