/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_simplesim_DeviceController */

#ifndef _Included_com_example_simplesim_DeviceController
#define _Included_com_example_simplesim_DeviceController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_simplesim_DeviceController
 * Method:    openSim
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_simplesim_DeviceController_openSim
  (JNIEnv *, jobject);

/*
 * Class:     com_example_simplesim_DeviceController
 * Method:    closeSim
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_simplesim_DeviceController_closeSim
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_simplesim_DeviceController
 * Method:    writeToDevice
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_simplesim_DeviceController_writeToDevice
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_example_simplesim_DeviceController
 * Method:    ioctlSetSim
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_simplesim_DeviceController_ioctlSetSim
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     com_example_simplesim_DeviceController
 * Method:    ioctlCmdSim
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_simplesim_DeviceController_ioctlCmdSim
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_example_simplesim_DeviceController
 * Method:    openSimInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_simplesim_DeviceController_openSimInt
  (JNIEnv *, jobject);

/*
 * Class:     com_example_simplesim_DeviceController
 * Method:    closeSimInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_simplesim_DeviceController_closeSimInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_simplesim_DeviceController
 * Method:    readInterrupt
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_simplesim_DeviceController_readInterrupt
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
